export const USERNAME_NOT_INITIALIZED = 0
export const USERNAME_EMPTY = 1
export const USERNAME_OK = 2
export const USERNAME_ALREADY_EXISTS = 3

export const PASSWORD_NOT_INITIALIZED = 0
export const PASSWORD_EMPTY = 1
export const PASSWORD_OK = 2

export const CONFIRM_PASSWORD_NOT_INITIALIZED = 0
export const CONFIRM_PASSWORD_EMPTY = 1
export const CONFIRM_PASSWORD_MATCHED = 2
export const CONFIRM_PASSWORD_NOT_MATCHED = 3